platform :ios, '9.0'

target 'NativeDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Flutter',:podspec => 'Flutter/Debug/Flutter.podspec'
  # Pods for NativeDemo

end
